title: "Jekyll-Data-Test"
repo: "https://github.com/vzvenyach/jekyll-data-test"

name: "Jekyll-Data-Test"
description: "A test of `data_source`"
url: http://code.esq.io/jekyll-data-test

markdown: kramdown

data_source: api

baseurl: /jekyll-data-test